name: Calculator Deployment

on: push

jobs:
  receipt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      
      - run: echo "========================================"
      - run: echo "           Deployment Reciept           "
      - run: echo "========================================"
      - run: echo "Repository - ${{ github.repository }}"
      - run: echo "Branch - ${{ github.ref_name }}"
      - run: echo "Triggered by - ${{ github.actor }}"
      - run: echo "Event Type - ${{ github.event_name }} "
      - run: echo "Timestamp - $(date)" 
      - run: echo "========================================"