name: Calculator Deployment

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo " Runner name ${{ runner.name }} "
      - run: echo "Hello ${{ github.actor }}"
      - run: echo "You pushed to main- $(branch) from repository ${{ github.repository }}"
      - run: echo "Current date and time $(date)"